# Generated by Django 4.2.1 on 2023-05-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gerät',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(max_length=50)),
                ('anzahl', models.IntegerField()),
                ('seriennummer', models.CharField(max_length=50)),
                ('artikelnummer', models.CharField(max_length=50)),
                ('preis', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
