# Generated by Django 4.2.1 on 2023-05-21 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_verkauf'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('anzahl', models.IntegerField(default=1)),
                ('artikel_nr', models.CharField(blank=True, max_length=200, null=True)),
                ('einkaufsdatum', models.DateField(blank=True, null=True)),
                ('preis', models.FloatField(blank=True, null=True)),
                ('energie', models.CharField(blank=True, max_length=10, null=True)),
                ('bestellungsnummer', models.IntegerField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True)),
                ('farbe', models.CharField(blank=True, max_length=50, null=True)),
                ('Beschreibung', models.TextField(blank=True, max_length=5000, null=True)),
                ('note', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='verkauf',
            name='artikelnummer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='verkauf',
            name='marke',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='verkauf',
            name='preis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='verkauf',
            name='seriennummer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verkauf',
            name='gerät',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.gerät'),
        ),
        migrations.CreateModel(
            name='Kuehlschrank',
            fields=[
                ('basicinformation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.basicinformation')),
                ('type', models.CharField(choices=[('Kombi', 'Kombi'), ('Nur Kuehlen', 'Nur Kuehlen'), ('Nur Gefrier', 'Nur Gefrier'), ('Mini Kühlschrank mit Gefrierfach', 'Mini Kühlschrank mit Gefrierfach'), ('Mini Kühlschrank ohne Gefrierfach', 'Mini Kühlschrank ohne Gefrierfach'), ('Mini nur Gefrier', 'Mini nur Gefrier'), ('Gefrierbox', 'Gefrierbox'), ('Kühlbox', 'Kühlbox'), ('Side-By-Side', 'Side-By-Side'), ('other', 'other')], max_length=200)),
            ],
            bases=('inventory.basicinformation',),
        ),
        migrations.CreateModel(
            name='Spuelmaschine',
            fields=[
                ('basicinformation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.basicinformation')),
                ('breite', models.CharField(choices=[('45 cm', '45 cm'), ('60 cm', '60 cm'), ('other', 'other')], max_length=100)),
                ('art', models.CharField(choices=[('Vollintegriert', 'Vollintegriert'), ('Teilintegriert', 'Teilintegriert'), ('Standgerät', 'Standgerät'), ('Unterbau', 'Unterbau'), ('Tischgerät', 'Tischgerät'), ('other', 'other')], max_length=100)),
            ],
            bases=('inventory.basicinformation',),
        ),
        migrations.CreateModel(
            name='Waschmaschine',
            fields=[
                ('basicinformation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.basicinformation')),
                ('fassung', models.CharField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('mehr', 'mehr')], max_length=20)),
                ('toploader', models.CharField(choices=[('Ja', 'Ja'), ('Nein', 'Nein')], default='Nein', max_length=5)),
            ],
            bases=('inventory.basicinformation',),
        ),
        migrations.AddField(
            model_name='verkauf',
            name='kuhlschrank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.kuehlschrank'),
        ),
        migrations.AddField(
            model_name='verkauf',
            name='spuelmaschine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.spuelmaschine'),
        ),
        migrations.AddField(
            model_name='verkauf',
            name='waschmaschine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.waschmaschine'),
        ),
    ]
